config/routes.rb
Rails.application.routes.draw do

#Static Pages Routes
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'resources', to: 'pages#resources'
#Default Homepage route
  root 'home#index'
#All other controllers routes
  resources :posts
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # attr_accessible :name
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  # attr_accessible :title, :body, :category_id, :author_id
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @post = @category.posts

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @post = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @category_posts = @post.category
  end

  # def new
  #   @post = Post.new()
  #   @category = Category.all

  # end

  # def create
  #   @post = Post.create(post_params)
  #   if @post.save
  #     redirect_to posts_path, notice: "Post was created successfully"
  #   else
  #     render new
  #   end

  # end

  # def edit
  #   @post = Post.find(params[:id])
  # end

  # def update
  #   @post = Post.find(params[:id])
  #   if @post.update(post_params)

  #     redirect_to post_path,
  #     :notice => "Your Post was Updated"
  #   else
  #     render "edit"
  #   end

  # end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path,
    :notice => "Your Post has been deleted"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<h1> Categories </h1>

<ul> <% @categories.each do |c| %> </ul>
<li> <%= link_to c.name, category_path(c) %> </li>
<% end %>

app/views/categories/show.html.erb
<h1> Category: <%= @category.name %> </h1>

<% if @post.empty? %>
  <p> Sorry, there are no posts currently.. </p>
<% else %>
  <% @post.each do |p| %>
  <h2><strong>Blog Title:</strong> <%= p.title %> <br/></h2>
  <p> <strong>Blog Body:</strong> <%= p.body %> <br/></p>
  <p> <small> Created at: <%= p.created_at %> <br/></small></p>
  <hr>
  <% end %>
<% end %>
<%= link_to "Back to Categories", categories_path %>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <!-- <h1>Welcome to Blog-Pages</h1> -->

      <% @post.each do |p| %>
      <div class="card">
        <ul><h1><%= p.title %></h1></ul>
          <ul><%= p.body %></ul>
          <ul><small><%= p.created_at.strftime("%A, %d %b %Y %l:%M %p") %></small></ul>
      </div>

          <% end %>
    </div>
  </div>
</div>


<!-- <div class="container">
  <div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-block">
        <h3 class="card-title">Special title treatment</h3>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-block">
        <h3 class="card-title">Special title treatment</h3>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
</div>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrubyblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- We can do a loop for notices here in the layouts which will display a confirmation message of a successful post being created -->
    <% flash.each do |key, value| %>
    <p> <%= value %> </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit: <%= @post.title %></h1>
<!-- we can create a partial for the form and use it everywhere -->
<%= form_for @post do |f| %>
<%= f.label :title %>
<%= f.text_field :title %> <br/><br/>

<%= f.label :body%> <br>
<%= f.text_area :body %> <br/><br/>


<%= f.select :category_id, Category.all.collect { |c| [c.name, c.id] } %> <br/><br/>

<%= f.submit "Update Post" %>

<%= link_to "Go Back", post_path, class: "btn btn-primary" %>

<% end %>

app/views/posts/index.html.erb
<!--  <%= flash[notice] %>  -->

<p>
  <%= link_to "Create a New Post", new_post_path %>
</p>

<p><% @posts.each do |post| %></p>
<h2><%= link_to post.title, post_path(post) %></h2>
<p><%= post.body %></p>
<hr>
<p><% end %></p>

app/views/posts/new.html.erb
<h1>Add a New Post</h1>

<%= form_for @post do |f| %>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>

<p>
  <%= f.select :category_id, Category.all.collect { |c| [c.name, c.id] }, {:include_blank => "Select One"} %>
</p>

<p>
  <%= f.submit "Create Post" %>
</p>

<% end %>

app/views/posts/show.html.erb
<%= flash[:notice] %>
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<small><%= @post.created_at.strftime("%A, %d %b %Y %l:%M %p") %></small><br/><br/>
<p>Category: <%= link_to @post.category.name, @category_posts %></p>
<%= link_to "Edit this Post", edit_post_path %>
<%= link_to "Delete Post", @post, data: { confirm: "Are you sure you want to delete?"}, :method => :delete %>
<%= link_to "Back", posts_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: "navbar_brand" do %>
        <%= image_tag "blog-pages.png" %>
      <% end %>
    </div>

  <ul class="nav nav-tabs">
    <li role="presentation" id="home"> <%= link_to "Home",root_path %></li>
    <li role="presentation" id="tab"> <%= link_to "Blog", posts_path %></li>
    <li role="presentation" id="tab"> <%= link_to "About", about_path %></li>
    <li role="presentation" id="tab"> <%= link_to "Contact", contact_path %></li>
    <li role="presentation" id="tab"> <%= link_to "Resources", resources_path%> </li>
  </ul>
  </div>

</nav>